version: '3'
services:
    db:
        image: "postgres"
        ports:
            - "${POSTGRES_PORT}:5432"
        env_file: 
            - .env
        volumes:
            - "dbdata:/var/lib/postgresql/data"
            - "./sql/init:/docker-entrypoint-initdb.d"
    app:
        build: .
        ports:
            - "${APP_EXTERNAL_PORT}:80"
        env_file: 
            - .env
volumes:
    dbdata: